project:
  type: website

publish:
  method: gh-pages
  branch: gh-pages

website:
  title: "Emma Boone — Sport- & Performancepsycholoog"
  site-url: "https://emmaboone.github.io"

lang: nl

format:
  html:
    theme: none
    css: styles.css
    page-layout: full
    include-in-header: _includes/head.html
    include-before-body: _includes/nav.html
    include-after-body: _includes/footer.html

resources:
  - images/web
  - icons
